In [17]:
import numpy as np
from sklearn import preprocessing
import numpy.linalg as linalg

## Singular Value Decomposition
### A[2 x 4] = U [2 x 2] S [2 x 4] V [4 x 4]

In [18]:
X = np.array([[-10, -10, 20, 20], [-10, 20, 20, -10]])
X.shape

(2, 4)

In [19]:
def svd(X):
    u = linalg.eig(X.dot(X.T))[1]
    s = np.sqrt(linalg.eig(X.dot(X.T))[0])
    v = linalg.eig(X.T.dot(X))[1]
    
    return u, s, v.T

In [20]:
U,S,V = svd(X)

In [21]:
print(U)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [22]:
print(S)

[33.1662479 30.       ]


In [23]:
print(V)

[[-4.26401433e-01  2.13200716e-01  8.52802865e-01  2.13200716e-01]
 [-8.83816675e-17  7.07106781e-01  1.05106397e-15 -7.07106781e-01]
 [ 4.42846691e-01  6.30508742e-01 -9.38310254e-02  6.30508742e-01]
 [ 3.99056487e-01 -5.53941596e-01  4.76499041e-01 -5.53941596e-01]]
